apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        deploymentTime: {{ now }}
      labels:
        {{- include "helm-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "helm-chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.env .Values.secretRef }}
          envFrom:
            {{- if .Values.env }}
            - configMapRef:
                name: {{ include "helm-chart.fullname" . }}
            {{- end }}
            {{- if .Values.secretRef }}
            - secretRef:
                name: {{ .Values.secretRef }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistentVolume }}
          volumeMounts:
            {{- range .Values.persistentVolume }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
      {{- if .Values.persistentVolume }}
      volumes:
        {{- range .Values.persistentVolume }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
      {{- end }}