{{- if .Values.service.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-node-port
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
{{- end }}