name: Release Helm Chart

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git tag history

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.2'

      - name: Get current chart version
        id: chart
        run: |
          CURRENT_VERSION=$(grep '^version:' ./service-deployer/Chart.yaml | awk '{print $2}')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Determine next version
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""  # No prefix at all

      - name: Update Chart.yaml version
        run: |
          sed -i "s/^version: .*/version: ${{ steps.version.outputs.new_tag }}/" ./service-deployer/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: ${{ steps.version.outputs.new_tag }}/" ./service-deployer/Chart.yaml  # Optional

      - name: Package Helm chart
        run: |
          helm package ./service-deployer -d ./packaged

      - name: Update Helm repo index
        run: |
          curl -sLO https://${{ github.repository_owner }}.github.io/${GITHUB_REPOSITORY#*/}/index.yaml || true
          [ -f index.yaml ] && mv index.yaml ./packaged/
          helm repo index ./packaged --url https://${{ github.repository_owner }}.github.io/${GITHUB_REPOSITORY#*/}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged
          destination_dir: ./
          force_orphan: true

      - name: Create Git tag
        run: |
          git tag ${{ steps.version.outputs.new_tag }}
          git push origin ${{ steps.version.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          files: |
            ./packaged/*.tgz
            ./packaged/index.yaml
          generate_release_notes: true